update menberlist
kufu/product-design-portal pull request #2
Opened 2023-06-27 07:24 UTC by drivesketch

2023-06-27 09:00 UTC, kgsi commented on src/components/MemberList.astro
> +    description: 'デザインエンジニア。プロ兼務ニスト。 ',
```suggestion
    description: 'デザインエンジニア。タレントマネジメント担当。兼務して仕事をするのが癖になってる ',
```

2023-06-28 08:50 UTC, ouji-miyahara commented on src/components/MemberList.astro
> +    description: 'UI デザイナー。VP of Product Design。 ',
```suggestion
    description: 'VP of Product Design。催眠術が得意です。 ',
```

2023-06-29 01:22 UTC, wentzzz commented on src/components/MemberList.astro
> +    description: 'プロダクトデザイナー。 ',
```suggestion
    description: 'プロダクトデザイナー。人事・労務領域担当。Figmaオタク。 ',
```

2023-07-05 07:40 UTC, oremega commented on src/components/MemberList.astro
> +    description: 'UI デザイナー。リサーチ推進室主催。 ',
```suggestion
    description: 'UI デザイナー。 労務領域担当。ユーザーリサーチ推進室室長。',
```

2023-07-06 06:20 UTC, tosiiu commented on src/components/MemberList.astro
> +    description: 'プロダクトデザイナー。 ',
```suggestion
    description: 'プロダクトデザイナー。タレントマネジメント領域担当。Evilなことが嫌い。 ',
```

2023-07-10 02:48 UTC, ayumizu commented on src/components/MemberList.astro
> +    description: 'UI デザイナー。 ',
```suggestion
    description: 'UI デザイナー。企業向けSaaSの仕様決めとUIデザインが好き。',
```

2023-07-10 02:51 UTC, versionfive commented on src/components/MemberList.astro
> +    description: 'UX デザイナー。UX 警察。 ',
```suggestion
    description: 'UXデザイナー。新規プロダクトやデザインシステムを担当。',
```

2023-07-10 02:56 UTC, daxelbook requested changes, later dismissed

2023-07-10 02:56 UTC, daxelbook commented on src/components/MemberList.astro
> +    description: 'UI デザイナー。デザインはもちろんサーバーサイドやフロントエンドの実装やQAも行うプロダクト開発のスペシャリスト。 ',
```suggestion
    description: 'UIが好きな男',
```

2023-07-18 03:30 UTC, merged